name: linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install CVMFS
      run: |
        wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
        sudo dpkg -i cvmfs-release-latest_all.deb
        sudo apt-get update
        sudo apt-get install cvmfs cvmfs-config-default
        sudo cvmfs_config setup
        echo "CVMFS_QUOTA_LIMIT='32140'" > default.local
        echo "CVMFS_HTTP_PROXY=DIRECT" >> default.local
        echo "CVMFS_CACHE_BASE='/var/lib/cvmfs'" >> default.local
        echo "CVMFS_FORCE_SIGNING='yes'" >> default.local
        echo "CVMFS_FOLLOW_REDIRECTS='yes'" >> default.local
        echo "CVMFS_REPOSITORIES='sw.hsf.org,sw-nightlies.hsf.org,fcc.cern.ch,sft-nightlies.cern.ch,sft.cern.ch,geant4.cern.ch'" >> default.local
        echo "CVMFS_SEND_INFO_HEADER=no" >> default.local
        sudo mkdir -p /etc/cvmfs
        sudo mv default.local /etc/cvmfs/default.local
        sudo cvmfs_config probe
        ls /cvmfs/sft.cern.ch
        ls /cvmfs/fcc.cern.ch
        ls /cvmfs/geant4.cern.ch/share/data/
        ls /cvmfs/geant4.cern.ch/share/data/G4ENSDFSTATE2.2
        #export CVMFS_REPOS="-v /cvmfs/sft.cern.ch:/cvmfs/sft.cern.ch"
        #export CVMFS_REPOS="${CVMFS_REPOS} -v /cvmfs/sw-nightlies.hsf.org:/cvmfs/sw-nightlies.hsf.org"
        #export CVMFS_REPOS="${CVMFS_REPOS} -v /cvmfs/sw.hsf.org:/cvmfs/sw.hsf.org"
        #export CVMFS_REPOS="${CVMFS_REPOS} -v /cvmfs/geant4.cern.ch:/cvmfs/geant4.cern.ch"
        #export CVMFS_REPOS="${CVMFS_REPOS} -v /cvmfs/fcc.cern.ch:/cvmfs/fcc.cern.ch"
        #shopt -s extglob dotglob
        #mkdir Package
        #mv !(Package) Package
        #shopt -u dotglob
        #export PKGDIR=${PWD}/Package


    - name: Start container
      run: |
        docker run -it --name CI_container -v ${GITHUB_WORKSPACE}:/Package -v /cvmfs:/cvmfs -d clicdp/cc7-lcg /bin/bash
    - name: Compile and test
      run: |
        #docker exec CI_container /bin/bash -c "ln -s /usr/lib64/liblzma.so.5.2.2 /usr/lib64/liblzma.so; ./Package/.github/scripts/compile_and_test.sh"
        docker exec CI_container /bin/bash -c "ln -s /usr/lib64/liblzma.so.5.2.2 /usr/lib64/liblzma.so;cd ./Package; ls -alh /cvmfs/geant4.cern.ch/share/data; ls -alh /cvmfs/geant4.cern.ch/; source init.sh; ls -alh $G4PARTICLEXSDATA; echo 'try datasets'; /cvmfs/sft.cern.ch/lcg/views/LCG_97_FCC_2/x86_64-centos7-gcc8-opt/bin/geant4-config --datasets"
